// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

/**
 * <pre>
 * Notify scheduler elevator is moving
 * </pre>
 *
 * Protobuf type {@code elevatorCommands.ElevatorDepartureMessage}
 */
public final class ElevatorDepartureMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorCommands.ElevatorDepartureMessage)
    ElevatorDepartureMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ElevatorDepartureMessage.newBuilder() to construct.
  private ElevatorDepartureMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ElevatorDepartureMessage() {
    direction_ = 0;
    timeStamp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ElevatorDepartureMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ElevatorDepartureMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            elevatorID_ = input.readUInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          case 24: {

            initialFloor_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            timeStamp_ = s;
            break;
          }
          case 40: {

            requestID_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return elevatorCommands.ElevatorCommandProtos.internal_static_elevatorCommands_ElevatorDepartureMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return elevatorCommands.ElevatorCommandProtos.internal_static_elevatorCommands_ElevatorDepartureMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            elevatorCommands.ElevatorDepartureMessage.class, elevatorCommands.ElevatorDepartureMessage.Builder.class);
  }

  public static final int ELEVATORID_FIELD_NUMBER = 1;
  private int elevatorID_;
  /**
   * <code>uint32 elevatorID = 1;</code>
   * @return The elevatorID.
   */
  @java.lang.Override
  public int getElevatorID() {
    return elevatorID_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  private int direction_;
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The direction.
   */
  @java.lang.Override public elevatorCommands.Direction getDirection() {
    @SuppressWarnings("deprecation")
    elevatorCommands.Direction result = elevatorCommands.Direction.valueOf(direction_);
    return result == null ? elevatorCommands.Direction.UNRECOGNIZED : result;
  }

  public static final int INITIALFLOOR_FIELD_NUMBER = 3;
  private int initialFloor_;
  /**
   * <code>uint32 initialFloor = 3;</code>
   * @return The initialFloor.
   */
  @java.lang.Override
  public int getInitialFloor() {
    return initialFloor_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private volatile java.lang.Object timeStamp_;
  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public java.lang.String getTimeStamp() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeStamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeStampBytes() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeStamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUESTID_FIELD_NUMBER = 5;
  private int requestID_;
  /**
   * <code>uint32 requestID = 5;</code>
   * @return The requestID.
   */
  @java.lang.Override
  public int getRequestID() {
    return requestID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (elevatorID_ != 0) {
      output.writeUInt32(1, elevatorID_);
    }
    if (direction_ != elevatorCommands.Direction.UP.getNumber()) {
      output.writeEnum(2, direction_);
    }
    if (initialFloor_ != 0) {
      output.writeUInt32(3, initialFloor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timeStamp_);
    }
    if (requestID_ != 0) {
      output.writeUInt32(5, requestID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (elevatorID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, elevatorID_);
    }
    if (direction_ != elevatorCommands.Direction.UP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, direction_);
    }
    if (initialFloor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, initialFloor_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timeStamp_);
    }
    if (requestID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, requestID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof elevatorCommands.ElevatorDepartureMessage)) {
      return super.equals(obj);
    }
    elevatorCommands.ElevatorDepartureMessage other = (elevatorCommands.ElevatorDepartureMessage) obj;

    if (getElevatorID()
        != other.getElevatorID()) return false;
    if (direction_ != other.direction_) return false;
    if (getInitialFloor()
        != other.getInitialFloor()) return false;
    if (!getTimeStamp()
        .equals(other.getTimeStamp())) return false;
    if (getRequestID()
        != other.getRequestID()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ELEVATORID_FIELD_NUMBER;
    hash = (53 * hash) + getElevatorID();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (37 * hash) + INITIALFLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getInitialFloor();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStamp().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static elevatorCommands.ElevatorDepartureMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(elevatorCommands.ElevatorDepartureMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Notify scheduler elevator is moving
   * </pre>
   *
   * Protobuf type {@code elevatorCommands.ElevatorDepartureMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorCommands.ElevatorDepartureMessage)
      elevatorCommands.ElevatorDepartureMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return elevatorCommands.ElevatorCommandProtos.internal_static_elevatorCommands_ElevatorDepartureMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return elevatorCommands.ElevatorCommandProtos.internal_static_elevatorCommands_ElevatorDepartureMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              elevatorCommands.ElevatorDepartureMessage.class, elevatorCommands.ElevatorDepartureMessage.Builder.class);
    }

    // Construct using elevatorCommands.ElevatorDepartureMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      elevatorID_ = 0;

      direction_ = 0;

      initialFloor_ = 0;

      timeStamp_ = "";

      requestID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return elevatorCommands.ElevatorCommandProtos.internal_static_elevatorCommands_ElevatorDepartureMessage_descriptor;
    }

    @java.lang.Override
    public elevatorCommands.ElevatorDepartureMessage getDefaultInstanceForType() {
      return elevatorCommands.ElevatorDepartureMessage.getDefaultInstance();
    }

    @java.lang.Override
    public elevatorCommands.ElevatorDepartureMessage build() {
      elevatorCommands.ElevatorDepartureMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public elevatorCommands.ElevatorDepartureMessage buildPartial() {
      elevatorCommands.ElevatorDepartureMessage result = new elevatorCommands.ElevatorDepartureMessage(this);
      result.elevatorID_ = elevatorID_;
      result.direction_ = direction_;
      result.initialFloor_ = initialFloor_;
      result.timeStamp_ = timeStamp_;
      result.requestID_ = requestID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof elevatorCommands.ElevatorDepartureMessage) {
        return mergeFrom((elevatorCommands.ElevatorDepartureMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(elevatorCommands.ElevatorDepartureMessage other) {
      if (other == elevatorCommands.ElevatorDepartureMessage.getDefaultInstance()) return this;
      if (other.getElevatorID() != 0) {
        setElevatorID(other.getElevatorID());
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      if (other.getInitialFloor() != 0) {
        setInitialFloor(other.getInitialFloor());
      }
      if (!other.getTimeStamp().isEmpty()) {
        timeStamp_ = other.timeStamp_;
        onChanged();
      }
      if (other.getRequestID() != 0) {
        setRequestID(other.getRequestID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      elevatorCommands.ElevatorDepartureMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (elevatorCommands.ElevatorDepartureMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int elevatorID_ ;
    /**
     * <code>uint32 elevatorID = 1;</code>
     * @return The elevatorID.
     */
    @java.lang.Override
    public int getElevatorID() {
      return elevatorID_;
    }
    /**
     * <code>uint32 elevatorID = 1;</code>
     * @param value The elevatorID to set.
     * @return This builder for chaining.
     */
    public Builder setElevatorID(int value) {
      
      elevatorID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 elevatorID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearElevatorID() {
      
      elevatorID_ = 0;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return The direction.
     */
    @java.lang.Override
    public elevatorCommands.Direction getDirection() {
      @SuppressWarnings("deprecation")
      elevatorCommands.Direction result = elevatorCommands.Direction.valueOf(direction_);
      return result == null ? elevatorCommands.Direction.UNRECOGNIZED : result;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(elevatorCommands.Direction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int initialFloor_ ;
    /**
     * <code>uint32 initialFloor = 3;</code>
     * @return The initialFloor.
     */
    @java.lang.Override
    public int getInitialFloor() {
      return initialFloor_;
    }
    /**
     * <code>uint32 initialFloor = 3;</code>
     * @param value The initialFloor to set.
     * @return This builder for chaining.
     */
    public Builder setInitialFloor(int value) {
      
      initialFloor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 initialFloor = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitialFloor() {
      
      initialFloor_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timeStamp_ = "";
    /**
     * <code>string timeStamp = 4;</code>
     * @return The timeStamp.
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @return The bytes for timeStamp.
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = getDefaultInstance().getTimeStamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @param value The bytes for timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeStamp_ = value;
      onChanged();
      return this;
    }

    private int requestID_ ;
    /**
     * <code>uint32 requestID = 5;</code>
     * @return The requestID.
     */
    @java.lang.Override
    public int getRequestID() {
      return requestID_;
    }
    /**
     * <code>uint32 requestID = 5;</code>
     * @param value The requestID to set.
     * @return This builder for chaining.
     */
    public Builder setRequestID(int value) {
      
      requestID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 requestID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestID() {
      
      requestID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorCommands.ElevatorDepartureMessage)
  }

  // @@protoc_insertion_point(class_scope:elevatorCommands.ElevatorDepartureMessage)
  private static final elevatorCommands.ElevatorDepartureMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new elevatorCommands.ElevatorDepartureMessage();
  }

  public static elevatorCommands.ElevatorDepartureMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ElevatorDepartureMessage>
      PARSER = new com.google.protobuf.AbstractParser<ElevatorDepartureMessage>() {
    @java.lang.Override
    public ElevatorDepartureMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ElevatorDepartureMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ElevatorDepartureMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ElevatorDepartureMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public elevatorCommands.ElevatorDepartureMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

