// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

/**
 * Protobuf enum {@code elevatorCommands.LampState}
 */
public enum LampState
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ON = 0;</code>
   */
  ON(0),
  /**
   * <code>OFF = 1;</code>
   */
  OFF(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ON = 0;</code>
   */
  public static final int ON_VALUE = 0;
  /**
   * <code>OFF = 1;</code>
   */
  public static final int OFF_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LampState valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LampState forNumber(int value) {
    switch (value) {
      case 0: return ON;
      case 1: return OFF;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LampState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LampState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LampState>() {
          public LampState findValueByNumber(int number) {
            return LampState.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return elevatorCommands.ElevatorCommandProtos.getDescriptor().getEnumTypes().get(2);
  }

  private static final LampState[] VALUES = values();

  public static LampState valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LampState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:elevatorCommands.LampState)
}

