// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

public interface ElevatorFaultMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorCommands.ElevatorFaultMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 elevatorID = 1;</code>
   * @return The elevatorID.
   */
  int getElevatorID();

  /**
   * <code>.elevatorCommands.FaultType fault = 2;</code>
   * @return The enum numeric value on the wire for fault.
   */
  int getFaultValue();
  /**
   * <code>.elevatorCommands.FaultType fault = 2;</code>
   * @return The fault.
   */
  elevatorCommands.FaultType getFault();

  /**
   * <code>string timeStamp = 3;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 3;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();
}
