// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

public interface ElevatorDepartureMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorCommands.ElevatorDepartureMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 elevatorID = 1;</code>
   * @return The elevatorID.
   */
  int getElevatorID();

  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The direction.
   */
  elevatorCommands.Direction getDirection();

  /**
   * <code>uint32 initialFloor = 3;</code>
   * @return The initialFloor.
   */
  int getInitialFloor();

  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();

  /**
   * <code>uint32 requestID = 5;</code>
   * @return The requestID.
   */
  int getRequestID();
}
