// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

public interface LampMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorCommands.LampMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 floor = 1;</code>
   * @return The floor.
   */
  int getFloor();

  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  int getDirectionValue();
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The direction.
   */
  elevatorCommands.Direction getDirection();

  /**
   * <code>.elevatorCommands.LampState state = 3;</code>
   * @return The enum numeric value on the wire for state.
   */
  int getStateValue();
  /**
   * <code>.elevatorCommands.LampState state = 3;</code>
   * @return The state.
   */
  elevatorCommands.LampState getState();

  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();
}
