// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package elevatorCommands;

public interface WrapperMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorCommands.WrapperMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return Whether the elevatorRequest field is set.
   */
  boolean hasElevatorRequest();
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return The elevatorRequest.
   */
  elevatorCommands.ElevatorRequestMessage getElevatorRequest();
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   */
  elevatorCommands.ElevatorRequestMessageOrBuilder getElevatorRequestOrBuilder();

  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return Whether the schedulerDispatch field is set.
   */
  boolean hasSchedulerDispatch();
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return The schedulerDispatch.
   */
  elevatorCommands.SchedulerDispatchMessage getSchedulerDispatch();
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   */
  elevatorCommands.SchedulerDispatchMessageOrBuilder getSchedulerDispatchOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return Whether the elevatorArrived field is set.
   */
  boolean hasElevatorArrived();
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return The elevatorArrived.
   */
  elevatorCommands.ElevatorArrivedMessage getElevatorArrived();
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   */
  elevatorCommands.ElevatorArrivedMessageOrBuilder getElevatorArrivedOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return Whether the elevatorDeparture field is set.
   */
  boolean hasElevatorDeparture();
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return The elevatorDeparture.
   */
  elevatorCommands.ElevatorDepartureMessage getElevatorDeparture();
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   */
  elevatorCommands.ElevatorDepartureMessageOrBuilder getElevatorDepartureOrBuilder();

  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return Whether the floorSensor field is set.
   */
  boolean hasFloorSensor();
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return The floorSensor.
   */
  elevatorCommands.FloorSensorMessage getFloorSensor();
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   */
  elevatorCommands.FloorSensorMessageOrBuilder getFloorSensorOrBuilder();

  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return Whether the lampMessage field is set.
   */
  boolean hasLampMessage();
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return The lampMessage.
   */
  elevatorCommands.LampMessage getLampMessage();
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   */
  elevatorCommands.LampMessageOrBuilder getLampMessageOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return Whether the registerMessage field is set.
   */
  boolean hasRegisterMessage();
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return The registerMessage.
   */
  elevatorCommands.ElevatorRegisterMessage getRegisterMessage();
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   */
  elevatorCommands.ElevatorRegisterMessageOrBuilder getRegisterMessageOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorFaultMessage faultMessage = 8;</code>
   * @return Whether the faultMessage field is set.
   */
  boolean hasFaultMessage();
  /**
   * <code>.elevatorCommands.ElevatorFaultMessage faultMessage = 8;</code>
   * @return The faultMessage.
   */
  elevatorCommands.ElevatorFaultMessage getFaultMessage();
  /**
   * <code>.elevatorCommands.ElevatorFaultMessage faultMessage = 8;</code>
   */
  elevatorCommands.ElevatorFaultMessageOrBuilder getFaultMessageOrBuilder();

  public elevatorCommands.WrapperMessage.MsgCase getMsgCase();
}
