// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package message;

/**
 * Protobuf enum {@code elevatorCommands.FaultType}
 */
public enum FaultType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>DOORFAULT = 0;</code>
   */
  DOORFAULT(0),
  /**
   * <code>ELEVATOR_UNRESPONSIVE = 1;</code>
   */
  ELEVATOR_UNRESPONSIVE(1),
  /**
   * <code>SCHEDULE_FAULT = 2;</code>
   */
  SCHEDULE_FAULT(2),
  /**
   * <code>RESOLVED = 3;</code>
   */
  RESOLVED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>DOORFAULT = 0;</code>
   */
  public static final int DOORFAULT_VALUE = 0;
  /**
   * <code>ELEVATOR_UNRESPONSIVE = 1;</code>
   */
  public static final int ELEVATOR_UNRESPONSIVE_VALUE = 1;
  /**
   * <code>SCHEDULE_FAULT = 2;</code>
   */
  public static final int SCHEDULE_FAULT_VALUE = 2;
  /**
   * <code>RESOLVED = 3;</code>
   */
  public static final int RESOLVED_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static FaultType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static FaultType forNumber(int value) {
    switch (value) {
      case 0: return DOORFAULT;
      case 1: return ELEVATOR_UNRESPONSIVE;
      case 2: return SCHEDULE_FAULT;
      case 3: return RESOLVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<FaultType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      FaultType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<FaultType>() {
          public FaultType findValueByNumber(int number) {
            return FaultType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return message.ElevatorCommandProtos.getDescriptor().getEnumTypes().get(0);
  }

  private static final FaultType[] VALUES = values();

  public static FaultType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private FaultType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:elevatorCommands.FaultType)
}

