// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package message;

/**
 * <pre>
 * tell a floor to turn on lamp
 * </pre>
 *
 * Protobuf type {@code elevatorCommands.LampMessage}
 */
public final class LampMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorCommands.LampMessage)
    LampMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LampMessage.newBuilder() to construct.
  private LampMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LampMessage() {
    direction_ = 0;
    state_ = 0;
    timeStamp_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LampMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LampMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            floor_ = input.readUInt32();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            direction_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            state_ = rawValue;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            timeStamp_ = s;
            break;
          }
          case 40: {

            elevatorID_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return message.ElevatorCommandProtos.internal_static_elevatorCommands_LampMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return message.ElevatorCommandProtos.internal_static_elevatorCommands_LampMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            message.LampMessage.class, message.LampMessage.Builder.class);
  }

  public static final int FLOOR_FIELD_NUMBER = 1;
  private int floor_;
  /**
   * <code>uint32 floor = 1;</code>
   * @return The floor.
   */
  @java.lang.Override
  public int getFloor() {
    return floor_;
  }

  public static final int DIRECTION_FIELD_NUMBER = 2;
  private int direction_;
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The enum numeric value on the wire for direction.
   */
  @java.lang.Override public int getDirectionValue() {
    return direction_;
  }
  /**
   * <code>.elevatorCommands.Direction direction = 2;</code>
   * @return The direction.
   */
  @java.lang.Override public message.Direction getDirection() {
    @SuppressWarnings("deprecation")
    message.Direction result = message.Direction.valueOf(direction_);
    return result == null ? message.Direction.UNRECOGNIZED : result;
  }

  public static final int STATE_FIELD_NUMBER = 3;
  private int state_;
  /**
   * <code>.elevatorCommands.LampState state = 3;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.elevatorCommands.LampState state = 3;</code>
   * @return The state.
   */
  @java.lang.Override public message.LampState getState() {
    @SuppressWarnings("deprecation")
    message.LampState result = message.LampState.valueOf(state_);
    return result == null ? message.LampState.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 4;
  private volatile java.lang.Object timeStamp_;
  /**
   * <code>string timeStamp = 4;</code>
   * @return The timeStamp.
   */
  @java.lang.Override
  public java.lang.String getTimeStamp() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeStamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timeStamp = 4;</code>
   * @return The bytes for timeStamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeStampBytes() {
    java.lang.Object ref = timeStamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeStamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ELEVATORID_FIELD_NUMBER = 5;
  private int elevatorID_;
  /**
   * <code>uint32 elevatorID = 5;</code>
   * @return The elevatorID.
   */
  @java.lang.Override
  public int getElevatorID() {
    return elevatorID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (floor_ != 0) {
      output.writeUInt32(1, floor_);
    }
    if (direction_ != message.Direction.UP.getNumber()) {
      output.writeEnum(2, direction_);
    }
    if (state_ != message.LampState.ON.getNumber()) {
      output.writeEnum(3, state_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timeStamp_);
    }
    if (elevatorID_ != 0) {
      output.writeUInt32(5, elevatorID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (floor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, floor_);
    }
    if (direction_ != message.Direction.UP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, direction_);
    }
    if (state_ != message.LampState.ON.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, state_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeStamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timeStamp_);
    }
    if (elevatorID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, elevatorID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof message.LampMessage)) {
      return super.equals(obj);
    }
    message.LampMessage other = (message.LampMessage) obj;

    if (getFloor()
        != other.getFloor()) return false;
    if (direction_ != other.direction_) return false;
    if (state_ != other.state_) return false;
    if (!getTimeStamp()
        .equals(other.getTimeStamp())) return false;
    if (getElevatorID()
        != other.getElevatorID()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getFloor();
    hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
    hash = (53 * hash) + direction_;
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStamp().hashCode();
    hash = (37 * hash) + ELEVATORID_FIELD_NUMBER;
    hash = (53 * hash) + getElevatorID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static message.LampMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.LampMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.LampMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.LampMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.LampMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.LampMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.LampMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static message.LampMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static message.LampMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static message.LampMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static message.LampMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static message.LampMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(message.LampMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * tell a floor to turn on lamp
   * </pre>
   *
   * Protobuf type {@code elevatorCommands.LampMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorCommands.LampMessage)
      message.LampMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_LampMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_LampMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.LampMessage.class, message.LampMessage.Builder.class);
    }

    // Construct using elevatorCommands.LampMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      floor_ = 0;

      direction_ = 0;

      state_ = 0;

      timeStamp_ = "";

      elevatorID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_LampMessage_descriptor;
    }

    @java.lang.Override
    public message.LampMessage getDefaultInstanceForType() {
      return message.LampMessage.getDefaultInstance();
    }

    @java.lang.Override
    public message.LampMessage build() {
      message.LampMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public message.LampMessage buildPartial() {
      message.LampMessage result = new message.LampMessage(this);
      result.floor_ = floor_;
      result.direction_ = direction_;
      result.state_ = state_;
      result.timeStamp_ = timeStamp_;
      result.elevatorID_ = elevatorID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof message.LampMessage) {
        return mergeFrom((message.LampMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(message.LampMessage other) {
      if (other == message.LampMessage.getDefaultInstance()) return this;
      if (other.getFloor() != 0) {
        setFloor(other.getFloor());
      }
      if (other.direction_ != 0) {
        setDirectionValue(other.getDirectionValue());
      }
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (!other.getTimeStamp().isEmpty()) {
        timeStamp_ = other.timeStamp_;
        onChanged();
      }
      if (other.getElevatorID() != 0) {
        setElevatorID(other.getElevatorID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      message.LampMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (message.LampMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int floor_ ;
    /**
     * <code>uint32 floor = 1;</code>
     * @return The floor.
     */
    @java.lang.Override
    public int getFloor() {
      return floor_;
    }
    /**
     * <code>uint32 floor = 1;</code>
     * @param value The floor to set.
     * @return This builder for chaining.
     */
    public Builder setFloor(int value) {
      
      floor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 floor = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFloor() {
      
      floor_ = 0;
      onChanged();
      return this;
    }

    private int direction_ = 0;
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return The enum numeric value on the wire for direction.
     */
    @java.lang.Override public int getDirectionValue() {
      return direction_;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @param value The enum numeric value on the wire for direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirectionValue(int value) {
      
      direction_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return The direction.
     */
    @java.lang.Override
    public message.Direction getDirection() {
      @SuppressWarnings("deprecation")
      message.Direction result = message.Direction.valueOf(direction_);
      return result == null ? message.Direction.UNRECOGNIZED : result;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @param value The direction to set.
     * @return This builder for chaining.
     */
    public Builder setDirection(message.Direction value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      direction_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.Direction direction = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDirection() {
      
      direction_ = 0;
      onChanged();
      return this;
    }

    private int state_ = 0;
    /**
     * <code>.elevatorCommands.LampState state = 3;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.elevatorCommands.LampState state = 3;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      
      state_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.LampState state = 3;</code>
     * @return The state.
     */
    @java.lang.Override
    public message.LampState getState() {
      @SuppressWarnings("deprecation")
      message.LampState result = message.LampState.valueOf(state_);
      return result == null ? message.LampState.UNRECOGNIZED : result;
    }
    /**
     * <code>.elevatorCommands.LampState state = 3;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(message.LampState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.elevatorCommands.LampState state = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      
      state_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timeStamp_ = "";
    /**
     * <code>string timeStamp = 4;</code>
     * @return The timeStamp.
     */
    public java.lang.String getTimeStamp() {
      java.lang.Object ref = timeStamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @return The bytes for timeStamp.
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      java.lang.Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = getDefaultInstance().getTimeStamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timeStamp = 4;</code>
     * @param value The bytes for timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeStamp_ = value;
      onChanged();
      return this;
    }

    private int elevatorID_ ;
    /**
     * <code>uint32 elevatorID = 5;</code>
     * @return The elevatorID.
     */
    @java.lang.Override
    public int getElevatorID() {
      return elevatorID_;
    }
    /**
     * <code>uint32 elevatorID = 5;</code>
     * @param value The elevatorID to set.
     * @return This builder for chaining.
     */
    public Builder setElevatorID(int value) {
      
      elevatorID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 elevatorID = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearElevatorID() {
      
      elevatorID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorCommands.LampMessage)
  }

  // @@protoc_insertion_point(class_scope:elevatorCommands.LampMessage)
  private static final message.LampMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new message.LampMessage();
  }

  public static message.LampMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LampMessage>
      PARSER = new com.google.protobuf.AbstractParser<LampMessage>() {
    @java.lang.Override
    public LampMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LampMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LampMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LampMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public message.LampMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

