// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package message;

/**
 * <pre>
 * wrapper to send different message types
 * </pre>
 *
 * Protobuf type {@code elevatorCommands.WrapperMessage}
 */
public final class WrapperMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorCommands.WrapperMessage)
    WrapperMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WrapperMessage.newBuilder() to construct.
  private WrapperMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WrapperMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WrapperMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WrapperMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            message.ElevatorRequestMessage.Builder subBuilder = null;
            if (msgCase_ == 1) {
              subBuilder = ((message.ElevatorRequestMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.ElevatorRequestMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.ElevatorRequestMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 1;
            break;
          }
          case 18: {
            message.SchedulerDispatchMessage.Builder subBuilder = null;
            if (msgCase_ == 2) {
              subBuilder = ((message.SchedulerDispatchMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.SchedulerDispatchMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.SchedulerDispatchMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 2;
            break;
          }
          case 26: {
            message.ElevatorArrivedMessage.Builder subBuilder = null;
            if (msgCase_ == 3) {
              subBuilder = ((message.ElevatorArrivedMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.ElevatorArrivedMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.ElevatorArrivedMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 3;
            break;
          }
          case 34: {
            message.ElevatorDepartureMessage.Builder subBuilder = null;
            if (msgCase_ == 4) {
              subBuilder = ((message.ElevatorDepartureMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.ElevatorDepartureMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.ElevatorDepartureMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 4;
            break;
          }
          case 42: {
            message.FloorSensorMessage.Builder subBuilder = null;
            if (msgCase_ == 5) {
              subBuilder = ((message.FloorSensorMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.FloorSensorMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.FloorSensorMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 5;
            break;
          }
          case 50: {
            message.LampMessage.Builder subBuilder = null;
            if (msgCase_ == 6) {
              subBuilder = ((message.LampMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.LampMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.LampMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 6;
            break;
          }
          case 58: {
            message.ElevatorRegisterMessage.Builder subBuilder = null;
            if (msgCase_ == 7) {
              subBuilder = ((message.ElevatorRegisterMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.ElevatorRegisterMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.ElevatorRegisterMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 7;
            break;
          }
          case 66: {
            message.FaultMessage.Builder subBuilder = null;
            if (msgCase_ == 8) {
              subBuilder = ((message.FaultMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.FaultMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.FaultMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 8;
            break;
          }
          case 74: {
            message.SimulateFaultMessage.Builder subBuilder = null;
            if (msgCase_ == 9) {
              subBuilder = ((message.SimulateFaultMessage) msg_).toBuilder();
            }
            msg_ =
                input.readMessage(message.SimulateFaultMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((message.SimulateFaultMessage) msg_);
              msg_ = subBuilder.buildPartial();
            }
            msgCase_ = 9;
            break;
          }
          case 80: {

            tEST_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return message.ElevatorCommandProtos.internal_static_elevatorCommands_WrapperMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return message.ElevatorCommandProtos.internal_static_elevatorCommands_WrapperMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            message.WrapperMessage.class, message.WrapperMessage.Builder.class);
  }

  private int msgCase_ = 0;
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ELEVATORREQUEST(1),
    SCHEDULERDISPATCH(2),
    ELEVATORARRIVED(3),
    ELEVATORDEPARTURE(4),
    FLOORSENSOR(5),
    LAMPMESSAGE(6),
    REGISTERMESSAGE(7),
    FAULTMESSAGE(8),
    SIMFAULTMESSAGE(9),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return ELEVATORREQUEST;
        case 2: return SCHEDULERDISPATCH;
        case 3: return ELEVATORARRIVED;
        case 4: return ELEVATORDEPARTURE;
        case 5: return FLOORSENSOR;
        case 6: return LAMPMESSAGE;
        case 7: return REGISTERMESSAGE;
        case 8: return FAULTMESSAGE;
        case 9: return SIMFAULTMESSAGE;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int ELEVATORREQUEST_FIELD_NUMBER = 1;
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return Whether the elevatorRequest field is set.
   */
  @java.lang.Override
  public boolean hasElevatorRequest() {
    return msgCase_ == 1;
  }
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return The elevatorRequest.
   */
  @java.lang.Override
  public message.ElevatorRequestMessage getElevatorRequest() {
    if (msgCase_ == 1) {
       return (message.ElevatorRequestMessage) msg_;
    }
    return message.ElevatorRequestMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   */
  @java.lang.Override
  public message.ElevatorRequestMessageOrBuilder getElevatorRequestOrBuilder() {
    if (msgCase_ == 1) {
       return (message.ElevatorRequestMessage) msg_;
    }
    return message.ElevatorRequestMessage.getDefaultInstance();
  }

  public static final int SCHEDULERDISPATCH_FIELD_NUMBER = 2;
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return Whether the schedulerDispatch field is set.
   */
  @java.lang.Override
  public boolean hasSchedulerDispatch() {
    return msgCase_ == 2;
  }
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return The schedulerDispatch.
   */
  @java.lang.Override
  public message.SchedulerDispatchMessage getSchedulerDispatch() {
    if (msgCase_ == 2) {
       return (message.SchedulerDispatchMessage) msg_;
    }
    return message.SchedulerDispatchMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   */
  @java.lang.Override
  public message.SchedulerDispatchMessageOrBuilder getSchedulerDispatchOrBuilder() {
    if (msgCase_ == 2) {
       return (message.SchedulerDispatchMessage) msg_;
    }
    return message.SchedulerDispatchMessage.getDefaultInstance();
  }

  public static final int ELEVATORARRIVED_FIELD_NUMBER = 3;
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return Whether the elevatorArrived field is set.
   */
  @java.lang.Override
  public boolean hasElevatorArrived() {
    return msgCase_ == 3;
  }
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return The elevatorArrived.
   */
  @java.lang.Override
  public message.ElevatorArrivedMessage getElevatorArrived() {
    if (msgCase_ == 3) {
       return (message.ElevatorArrivedMessage) msg_;
    }
    return message.ElevatorArrivedMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   */
  @java.lang.Override
  public message.ElevatorArrivedMessageOrBuilder getElevatorArrivedOrBuilder() {
    if (msgCase_ == 3) {
       return (message.ElevatorArrivedMessage) msg_;
    }
    return message.ElevatorArrivedMessage.getDefaultInstance();
  }

  public static final int ELEVATORDEPARTURE_FIELD_NUMBER = 4;
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return Whether the elevatorDeparture field is set.
   */
  @java.lang.Override
  public boolean hasElevatorDeparture() {
    return msgCase_ == 4;
  }
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return The elevatorDeparture.
   */
  @java.lang.Override
  public message.ElevatorDepartureMessage getElevatorDeparture() {
    if (msgCase_ == 4) {
       return (message.ElevatorDepartureMessage) msg_;
    }
    return message.ElevatorDepartureMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   */
  @java.lang.Override
  public message.ElevatorDepartureMessageOrBuilder getElevatorDepartureOrBuilder() {
    if (msgCase_ == 4) {
       return (message.ElevatorDepartureMessage) msg_;
    }
    return message.ElevatorDepartureMessage.getDefaultInstance();
  }

  public static final int FLOORSENSOR_FIELD_NUMBER = 5;
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return Whether the floorSensor field is set.
   */
  @java.lang.Override
  public boolean hasFloorSensor() {
    return msgCase_ == 5;
  }
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return The floorSensor.
   */
  @java.lang.Override
  public message.FloorSensorMessage getFloorSensor() {
    if (msgCase_ == 5) {
       return (message.FloorSensorMessage) msg_;
    }
    return message.FloorSensorMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   */
  @java.lang.Override
  public message.FloorSensorMessageOrBuilder getFloorSensorOrBuilder() {
    if (msgCase_ == 5) {
       return (message.FloorSensorMessage) msg_;
    }
    return message.FloorSensorMessage.getDefaultInstance();
  }

  public static final int LAMPMESSAGE_FIELD_NUMBER = 6;
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return Whether the lampMessage field is set.
   */
  @java.lang.Override
  public boolean hasLampMessage() {
    return msgCase_ == 6;
  }
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return The lampMessage.
   */
  @java.lang.Override
  public message.LampMessage getLampMessage() {
    if (msgCase_ == 6) {
       return (message.LampMessage) msg_;
    }
    return message.LampMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   */
  @java.lang.Override
  public message.LampMessageOrBuilder getLampMessageOrBuilder() {
    if (msgCase_ == 6) {
       return (message.LampMessage) msg_;
    }
    return message.LampMessage.getDefaultInstance();
  }

  public static final int REGISTERMESSAGE_FIELD_NUMBER = 7;
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return Whether the registerMessage field is set.
   */
  @java.lang.Override
  public boolean hasRegisterMessage() {
    return msgCase_ == 7;
  }
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return The registerMessage.
   */
  @java.lang.Override
  public message.ElevatorRegisterMessage getRegisterMessage() {
    if (msgCase_ == 7) {
       return (message.ElevatorRegisterMessage) msg_;
    }
    return message.ElevatorRegisterMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   */
  @java.lang.Override
  public message.ElevatorRegisterMessageOrBuilder getRegisterMessageOrBuilder() {
    if (msgCase_ == 7) {
       return (message.ElevatorRegisterMessage) msg_;
    }
    return message.ElevatorRegisterMessage.getDefaultInstance();
  }

  public static final int FAULTMESSAGE_FIELD_NUMBER = 8;
  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   * @return Whether the faultMessage field is set.
   */
  @java.lang.Override
  public boolean hasFaultMessage() {
    return msgCase_ == 8;
  }
  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   * @return The faultMessage.
   */
  @java.lang.Override
  public message.FaultMessage getFaultMessage() {
    if (msgCase_ == 8) {
       return (message.FaultMessage) msg_;
    }
    return message.FaultMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   */
  @java.lang.Override
  public message.FaultMessageOrBuilder getFaultMessageOrBuilder() {
    if (msgCase_ == 8) {
       return (message.FaultMessage) msg_;
    }
    return message.FaultMessage.getDefaultInstance();
  }

  public static final int SIMFAULTMESSAGE_FIELD_NUMBER = 9;
  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   * @return Whether the simFaultMessage field is set.
   */
  @java.lang.Override
  public boolean hasSimFaultMessage() {
    return msgCase_ == 9;
  }
  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   * @return The simFaultMessage.
   */
  @java.lang.Override
  public message.SimulateFaultMessage getSimFaultMessage() {
    if (msgCase_ == 9) {
       return (message.SimulateFaultMessage) msg_;
    }
    return message.SimulateFaultMessage.getDefaultInstance();
  }
  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   */
  @java.lang.Override
  public message.SimulateFaultMessageOrBuilder getSimFaultMessageOrBuilder() {
    if (msgCase_ == 9) {
       return (message.SimulateFaultMessage) msg_;
    }
    return message.SimulateFaultMessage.getDefaultInstance();
  }

  public static final int TEST_FIELD_NUMBER = 10;
  private boolean tEST_;
  /**
   * <code>bool TEST = 10;</code>
   * @return The tEST.
   */
  @java.lang.Override
  public boolean getTEST() {
    return tEST_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (message.ElevatorRequestMessage) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (message.SchedulerDispatchMessage) msg_);
    }
    if (msgCase_ == 3) {
      output.writeMessage(3, (message.ElevatorArrivedMessage) msg_);
    }
    if (msgCase_ == 4) {
      output.writeMessage(4, (message.ElevatorDepartureMessage) msg_);
    }
    if (msgCase_ == 5) {
      output.writeMessage(5, (message.FloorSensorMessage) msg_);
    }
    if (msgCase_ == 6) {
      output.writeMessage(6, (message.LampMessage) msg_);
    }
    if (msgCase_ == 7) {
      output.writeMessage(7, (message.ElevatorRegisterMessage) msg_);
    }
    if (msgCase_ == 8) {
      output.writeMessage(8, (message.FaultMessage) msg_);
    }
    if (msgCase_ == 9) {
      output.writeMessage(9, (message.SimulateFaultMessage) msg_);
    }
    if (tEST_ != false) {
      output.writeBool(10, tEST_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (message.ElevatorRequestMessage) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (message.SchedulerDispatchMessage) msg_);
    }
    if (msgCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (message.ElevatorArrivedMessage) msg_);
    }
    if (msgCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (message.ElevatorDepartureMessage) msg_);
    }
    if (msgCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (message.FloorSensorMessage) msg_);
    }
    if (msgCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (message.LampMessage) msg_);
    }
    if (msgCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (message.ElevatorRegisterMessage) msg_);
    }
    if (msgCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (message.FaultMessage) msg_);
    }
    if (msgCase_ == 9) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, (message.SimulateFaultMessage) msg_);
    }
    if (tEST_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, tEST_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof message.WrapperMessage)) {
      return super.equals(obj);
    }
    message.WrapperMessage other = (message.WrapperMessage) obj;

    if (getTEST()
        != other.getTEST()) return false;
    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getElevatorRequest()
            .equals(other.getElevatorRequest())) return false;
        break;
      case 2:
        if (!getSchedulerDispatch()
            .equals(other.getSchedulerDispatch())) return false;
        break;
      case 3:
        if (!getElevatorArrived()
            .equals(other.getElevatorArrived())) return false;
        break;
      case 4:
        if (!getElevatorDeparture()
            .equals(other.getElevatorDeparture())) return false;
        break;
      case 5:
        if (!getFloorSensor()
            .equals(other.getFloorSensor())) return false;
        break;
      case 6:
        if (!getLampMessage()
            .equals(other.getLampMessage())) return false;
        break;
      case 7:
        if (!getRegisterMessage()
            .equals(other.getRegisterMessage())) return false;
        break;
      case 8:
        if (!getFaultMessage()
            .equals(other.getFaultMessage())) return false;
        break;
      case 9:
        if (!getSimFaultMessage()
            .equals(other.getSimFaultMessage())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getTEST());
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + ELEVATORREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getElevatorRequest().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SCHEDULERDISPATCH_FIELD_NUMBER;
        hash = (53 * hash) + getSchedulerDispatch().hashCode();
        break;
      case 3:
        hash = (37 * hash) + ELEVATORARRIVED_FIELD_NUMBER;
        hash = (53 * hash) + getElevatorArrived().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ELEVATORDEPARTURE_FIELD_NUMBER;
        hash = (53 * hash) + getElevatorDeparture().hashCode();
        break;
      case 5:
        hash = (37 * hash) + FLOORSENSOR_FIELD_NUMBER;
        hash = (53 * hash) + getFloorSensor().hashCode();
        break;
      case 6:
        hash = (37 * hash) + LAMPMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getLampMessage().hashCode();
        break;
      case 7:
        hash = (37 * hash) + REGISTERMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getRegisterMessage().hashCode();
        break;
      case 8:
        hash = (37 * hash) + FAULTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getFaultMessage().hashCode();
        break;
      case 9:
        hash = (37 * hash) + SIMFAULTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getSimFaultMessage().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static message.WrapperMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.WrapperMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.WrapperMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.WrapperMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.WrapperMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static message.WrapperMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static message.WrapperMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static message.WrapperMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static message.WrapperMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static message.WrapperMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static message.WrapperMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static message.WrapperMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(message.WrapperMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * wrapper to send different message types
   * </pre>
   *
   * Protobuf type {@code elevatorCommands.WrapperMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorCommands.WrapperMessage)
      message.WrapperMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_WrapperMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_WrapperMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.WrapperMessage.class, message.WrapperMessage.Builder.class);
    }

    // Construct using elevatorCommands.WrapperMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tEST_ = false;

      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return message.ElevatorCommandProtos.internal_static_elevatorCommands_WrapperMessage_descriptor;
    }

    @java.lang.Override
    public message.WrapperMessage getDefaultInstanceForType() {
      return message.WrapperMessage.getDefaultInstance();
    }

    @java.lang.Override
    public message.WrapperMessage build() {
      message.WrapperMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public message.WrapperMessage buildPartial() {
      message.WrapperMessage result = new message.WrapperMessage(this);
      if (msgCase_ == 1) {
        if (elevatorRequestBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = elevatorRequestBuilder_.build();
        }
      }
      if (msgCase_ == 2) {
        if (schedulerDispatchBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = schedulerDispatchBuilder_.build();
        }
      }
      if (msgCase_ == 3) {
        if (elevatorArrivedBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = elevatorArrivedBuilder_.build();
        }
      }
      if (msgCase_ == 4) {
        if (elevatorDepartureBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = elevatorDepartureBuilder_.build();
        }
      }
      if (msgCase_ == 5) {
        if (floorSensorBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = floorSensorBuilder_.build();
        }
      }
      if (msgCase_ == 6) {
        if (lampMessageBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = lampMessageBuilder_.build();
        }
      }
      if (msgCase_ == 7) {
        if (registerMessageBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = registerMessageBuilder_.build();
        }
      }
      if (msgCase_ == 8) {
        if (faultMessageBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = faultMessageBuilder_.build();
        }
      }
      if (msgCase_ == 9) {
        if (simFaultMessageBuilder_ == null) {
          result.msg_ = msg_;
        } else {
          result.msg_ = simFaultMessageBuilder_.build();
        }
      }
      result.tEST_ = tEST_;
      result.msgCase_ = msgCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof message.WrapperMessage) {
        return mergeFrom((message.WrapperMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(message.WrapperMessage other) {
      if (other == message.WrapperMessage.getDefaultInstance()) return this;
      if (other.getTEST() != false) {
        setTEST(other.getTEST());
      }
      switch (other.getMsgCase()) {
        case ELEVATORREQUEST: {
          mergeElevatorRequest(other.getElevatorRequest());
          break;
        }
        case SCHEDULERDISPATCH: {
          mergeSchedulerDispatch(other.getSchedulerDispatch());
          break;
        }
        case ELEVATORARRIVED: {
          mergeElevatorArrived(other.getElevatorArrived());
          break;
        }
        case ELEVATORDEPARTURE: {
          mergeElevatorDeparture(other.getElevatorDeparture());
          break;
        }
        case FLOORSENSOR: {
          mergeFloorSensor(other.getFloorSensor());
          break;
        }
        case LAMPMESSAGE: {
          mergeLampMessage(other.getLampMessage());
          break;
        }
        case REGISTERMESSAGE: {
          mergeRegisterMessage(other.getRegisterMessage());
          break;
        }
        case FAULTMESSAGE: {
          mergeFaultMessage(other.getFaultMessage());
          break;
        }
        case SIMFAULTMESSAGE: {
          mergeSimFaultMessage(other.getSimFaultMessage());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      message.WrapperMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (message.WrapperMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorRequestMessage, message.ElevatorRequestMessage.Builder, message.ElevatorRequestMessageOrBuilder> elevatorRequestBuilder_;
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     * @return Whether the elevatorRequest field is set.
     */
    @java.lang.Override
    public boolean hasElevatorRequest() {
      return msgCase_ == 1;
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     * @return The elevatorRequest.
     */
    @java.lang.Override
    public message.ElevatorRequestMessage getElevatorRequest() {
      if (elevatorRequestBuilder_ == null) {
        if (msgCase_ == 1) {
          return (message.ElevatorRequestMessage) msg_;
        }
        return message.ElevatorRequestMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return elevatorRequestBuilder_.getMessage();
        }
        return message.ElevatorRequestMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    public Builder setElevatorRequest(message.ElevatorRequestMessage value) {
      if (elevatorRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        elevatorRequestBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    public Builder setElevatorRequest(
        message.ElevatorRequestMessage.Builder builderForValue) {
      if (elevatorRequestBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        elevatorRequestBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    public Builder mergeElevatorRequest(message.ElevatorRequestMessage value) {
      if (elevatorRequestBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != message.ElevatorRequestMessage.getDefaultInstance()) {
          msg_ = message.ElevatorRequestMessage.newBuilder((message.ElevatorRequestMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          elevatorRequestBuilder_.mergeFrom(value);
        }
        elevatorRequestBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    public Builder clearElevatorRequest() {
      if (elevatorRequestBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        elevatorRequestBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    public message.ElevatorRequestMessage.Builder getElevatorRequestBuilder() {
      return getElevatorRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    @java.lang.Override
    public message.ElevatorRequestMessageOrBuilder getElevatorRequestOrBuilder() {
      if ((msgCase_ == 1) && (elevatorRequestBuilder_ != null)) {
        return elevatorRequestBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (message.ElevatorRequestMessage) msg_;
        }
        return message.ElevatorRequestMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorRequestMessage, message.ElevatorRequestMessage.Builder, message.ElevatorRequestMessageOrBuilder> 
        getElevatorRequestFieldBuilder() {
      if (elevatorRequestBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = message.ElevatorRequestMessage.getDefaultInstance();
        }
        elevatorRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.ElevatorRequestMessage, message.ElevatorRequestMessage.Builder, message.ElevatorRequestMessageOrBuilder>(
                (message.ElevatorRequestMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();;
      return elevatorRequestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.SchedulerDispatchMessage, message.SchedulerDispatchMessage.Builder, message.SchedulerDispatchMessageOrBuilder> schedulerDispatchBuilder_;
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     * @return Whether the schedulerDispatch field is set.
     */
    @java.lang.Override
    public boolean hasSchedulerDispatch() {
      return msgCase_ == 2;
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     * @return The schedulerDispatch.
     */
    @java.lang.Override
    public message.SchedulerDispatchMessage getSchedulerDispatch() {
      if (schedulerDispatchBuilder_ == null) {
        if (msgCase_ == 2) {
          return (message.SchedulerDispatchMessage) msg_;
        }
        return message.SchedulerDispatchMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return schedulerDispatchBuilder_.getMessage();
        }
        return message.SchedulerDispatchMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    public Builder setSchedulerDispatch(message.SchedulerDispatchMessage value) {
      if (schedulerDispatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        schedulerDispatchBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    public Builder setSchedulerDispatch(
        message.SchedulerDispatchMessage.Builder builderForValue) {
      if (schedulerDispatchBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        schedulerDispatchBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    public Builder mergeSchedulerDispatch(message.SchedulerDispatchMessage value) {
      if (schedulerDispatchBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != message.SchedulerDispatchMessage.getDefaultInstance()) {
          msg_ = message.SchedulerDispatchMessage.newBuilder((message.SchedulerDispatchMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          schedulerDispatchBuilder_.mergeFrom(value);
        }
        schedulerDispatchBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    public Builder clearSchedulerDispatch() {
      if (schedulerDispatchBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        schedulerDispatchBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    public message.SchedulerDispatchMessage.Builder getSchedulerDispatchBuilder() {
      return getSchedulerDispatchFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    @java.lang.Override
    public message.SchedulerDispatchMessageOrBuilder getSchedulerDispatchOrBuilder() {
      if ((msgCase_ == 2) && (schedulerDispatchBuilder_ != null)) {
        return schedulerDispatchBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (message.SchedulerDispatchMessage) msg_;
        }
        return message.SchedulerDispatchMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.SchedulerDispatchMessage, message.SchedulerDispatchMessage.Builder, message.SchedulerDispatchMessageOrBuilder> 
        getSchedulerDispatchFieldBuilder() {
      if (schedulerDispatchBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = message.SchedulerDispatchMessage.getDefaultInstance();
        }
        schedulerDispatchBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.SchedulerDispatchMessage, message.SchedulerDispatchMessage.Builder, message.SchedulerDispatchMessageOrBuilder>(
                (message.SchedulerDispatchMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();;
      return schedulerDispatchBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorArrivedMessage, message.ElevatorArrivedMessage.Builder, message.ElevatorArrivedMessageOrBuilder> elevatorArrivedBuilder_;
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     * @return Whether the elevatorArrived field is set.
     */
    @java.lang.Override
    public boolean hasElevatorArrived() {
      return msgCase_ == 3;
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     * @return The elevatorArrived.
     */
    @java.lang.Override
    public message.ElevatorArrivedMessage getElevatorArrived() {
      if (elevatorArrivedBuilder_ == null) {
        if (msgCase_ == 3) {
          return (message.ElevatorArrivedMessage) msg_;
        }
        return message.ElevatorArrivedMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 3) {
          return elevatorArrivedBuilder_.getMessage();
        }
        return message.ElevatorArrivedMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    public Builder setElevatorArrived(message.ElevatorArrivedMessage value) {
      if (elevatorArrivedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        elevatorArrivedBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    public Builder setElevatorArrived(
        message.ElevatorArrivedMessage.Builder builderForValue) {
      if (elevatorArrivedBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        elevatorArrivedBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    public Builder mergeElevatorArrived(message.ElevatorArrivedMessage value) {
      if (elevatorArrivedBuilder_ == null) {
        if (msgCase_ == 3 &&
            msg_ != message.ElevatorArrivedMessage.getDefaultInstance()) {
          msg_ = message.ElevatorArrivedMessage.newBuilder((message.ElevatorArrivedMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 3) {
          elevatorArrivedBuilder_.mergeFrom(value);
        }
        elevatorArrivedBuilder_.setMessage(value);
      }
      msgCase_ = 3;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    public Builder clearElevatorArrived() {
      if (elevatorArrivedBuilder_ == null) {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 3) {
          msgCase_ = 0;
          msg_ = null;
        }
        elevatorArrivedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    public message.ElevatorArrivedMessage.Builder getElevatorArrivedBuilder() {
      return getElevatorArrivedFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    @java.lang.Override
    public message.ElevatorArrivedMessageOrBuilder getElevatorArrivedOrBuilder() {
      if ((msgCase_ == 3) && (elevatorArrivedBuilder_ != null)) {
        return elevatorArrivedBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 3) {
          return (message.ElevatorArrivedMessage) msg_;
        }
        return message.ElevatorArrivedMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorArrivedMessage, message.ElevatorArrivedMessage.Builder, message.ElevatorArrivedMessageOrBuilder> 
        getElevatorArrivedFieldBuilder() {
      if (elevatorArrivedBuilder_ == null) {
        if (!(msgCase_ == 3)) {
          msg_ = message.ElevatorArrivedMessage.getDefaultInstance();
        }
        elevatorArrivedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.ElevatorArrivedMessage, message.ElevatorArrivedMessage.Builder, message.ElevatorArrivedMessageOrBuilder>(
                (message.ElevatorArrivedMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 3;
      onChanged();;
      return elevatorArrivedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorDepartureMessage, message.ElevatorDepartureMessage.Builder, message.ElevatorDepartureMessageOrBuilder> elevatorDepartureBuilder_;
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     * @return Whether the elevatorDeparture field is set.
     */
    @java.lang.Override
    public boolean hasElevatorDeparture() {
      return msgCase_ == 4;
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     * @return The elevatorDeparture.
     */
    @java.lang.Override
    public message.ElevatorDepartureMessage getElevatorDeparture() {
      if (elevatorDepartureBuilder_ == null) {
        if (msgCase_ == 4) {
          return (message.ElevatorDepartureMessage) msg_;
        }
        return message.ElevatorDepartureMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 4) {
          return elevatorDepartureBuilder_.getMessage();
        }
        return message.ElevatorDepartureMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    public Builder setElevatorDeparture(message.ElevatorDepartureMessage value) {
      if (elevatorDepartureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        elevatorDepartureBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    public Builder setElevatorDeparture(
        message.ElevatorDepartureMessage.Builder builderForValue) {
      if (elevatorDepartureBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        elevatorDepartureBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    public Builder mergeElevatorDeparture(message.ElevatorDepartureMessage value) {
      if (elevatorDepartureBuilder_ == null) {
        if (msgCase_ == 4 &&
            msg_ != message.ElevatorDepartureMessage.getDefaultInstance()) {
          msg_ = message.ElevatorDepartureMessage.newBuilder((message.ElevatorDepartureMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 4) {
          elevatorDepartureBuilder_.mergeFrom(value);
        }
        elevatorDepartureBuilder_.setMessage(value);
      }
      msgCase_ = 4;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    public Builder clearElevatorDeparture() {
      if (elevatorDepartureBuilder_ == null) {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 4) {
          msgCase_ = 0;
          msg_ = null;
        }
        elevatorDepartureBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    public message.ElevatorDepartureMessage.Builder getElevatorDepartureBuilder() {
      return getElevatorDepartureFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    @java.lang.Override
    public message.ElevatorDepartureMessageOrBuilder getElevatorDepartureOrBuilder() {
      if ((msgCase_ == 4) && (elevatorDepartureBuilder_ != null)) {
        return elevatorDepartureBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 4) {
          return (message.ElevatorDepartureMessage) msg_;
        }
        return message.ElevatorDepartureMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorDepartureMessage, message.ElevatorDepartureMessage.Builder, message.ElevatorDepartureMessageOrBuilder> 
        getElevatorDepartureFieldBuilder() {
      if (elevatorDepartureBuilder_ == null) {
        if (!(msgCase_ == 4)) {
          msg_ = message.ElevatorDepartureMessage.getDefaultInstance();
        }
        elevatorDepartureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.ElevatorDepartureMessage, message.ElevatorDepartureMessage.Builder, message.ElevatorDepartureMessageOrBuilder>(
                (message.ElevatorDepartureMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 4;
      onChanged();;
      return elevatorDepartureBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.FloorSensorMessage, message.FloorSensorMessage.Builder, message.FloorSensorMessageOrBuilder> floorSensorBuilder_;
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     * @return Whether the floorSensor field is set.
     */
    @java.lang.Override
    public boolean hasFloorSensor() {
      return msgCase_ == 5;
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     * @return The floorSensor.
     */
    @java.lang.Override
    public message.FloorSensorMessage getFloorSensor() {
      if (floorSensorBuilder_ == null) {
        if (msgCase_ == 5) {
          return (message.FloorSensorMessage) msg_;
        }
        return message.FloorSensorMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 5) {
          return floorSensorBuilder_.getMessage();
        }
        return message.FloorSensorMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    public Builder setFloorSensor(message.FloorSensorMessage value) {
      if (floorSensorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        floorSensorBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    public Builder setFloorSensor(
        message.FloorSensorMessage.Builder builderForValue) {
      if (floorSensorBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        floorSensorBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    public Builder mergeFloorSensor(message.FloorSensorMessage value) {
      if (floorSensorBuilder_ == null) {
        if (msgCase_ == 5 &&
            msg_ != message.FloorSensorMessage.getDefaultInstance()) {
          msg_ = message.FloorSensorMessage.newBuilder((message.FloorSensorMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 5) {
          floorSensorBuilder_.mergeFrom(value);
        }
        floorSensorBuilder_.setMessage(value);
      }
      msgCase_ = 5;
      return this;
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    public Builder clearFloorSensor() {
      if (floorSensorBuilder_ == null) {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 5) {
          msgCase_ = 0;
          msg_ = null;
        }
        floorSensorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    public message.FloorSensorMessage.Builder getFloorSensorBuilder() {
      return getFloorSensorFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    @java.lang.Override
    public message.FloorSensorMessageOrBuilder getFloorSensorOrBuilder() {
      if ((msgCase_ == 5) && (floorSensorBuilder_ != null)) {
        return floorSensorBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 5) {
          return (message.FloorSensorMessage) msg_;
        }
        return message.FloorSensorMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.FloorSensorMessage, message.FloorSensorMessage.Builder, message.FloorSensorMessageOrBuilder> 
        getFloorSensorFieldBuilder() {
      if (floorSensorBuilder_ == null) {
        if (!(msgCase_ == 5)) {
          msg_ = message.FloorSensorMessage.getDefaultInstance();
        }
        floorSensorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.FloorSensorMessage, message.FloorSensorMessage.Builder, message.FloorSensorMessageOrBuilder>(
                (message.FloorSensorMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 5;
      onChanged();;
      return floorSensorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.LampMessage, message.LampMessage.Builder, message.LampMessageOrBuilder> lampMessageBuilder_;
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     * @return Whether the lampMessage field is set.
     */
    @java.lang.Override
    public boolean hasLampMessage() {
      return msgCase_ == 6;
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     * @return The lampMessage.
     */
    @java.lang.Override
    public message.LampMessage getLampMessage() {
      if (lampMessageBuilder_ == null) {
        if (msgCase_ == 6) {
          return (message.LampMessage) msg_;
        }
        return message.LampMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 6) {
          return lampMessageBuilder_.getMessage();
        }
        return message.LampMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    public Builder setLampMessage(message.LampMessage value) {
      if (lampMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        lampMessageBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    public Builder setLampMessage(
        message.LampMessage.Builder builderForValue) {
      if (lampMessageBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        lampMessageBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    public Builder mergeLampMessage(message.LampMessage value) {
      if (lampMessageBuilder_ == null) {
        if (msgCase_ == 6 &&
            msg_ != message.LampMessage.getDefaultInstance()) {
          msg_ = message.LampMessage.newBuilder((message.LampMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 6) {
          lampMessageBuilder_.mergeFrom(value);
        }
        lampMessageBuilder_.setMessage(value);
      }
      msgCase_ = 6;
      return this;
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    public Builder clearLampMessage() {
      if (lampMessageBuilder_ == null) {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 6) {
          msgCase_ = 0;
          msg_ = null;
        }
        lampMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    public message.LampMessage.Builder getLampMessageBuilder() {
      return getLampMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    @java.lang.Override
    public message.LampMessageOrBuilder getLampMessageOrBuilder() {
      if ((msgCase_ == 6) && (lampMessageBuilder_ != null)) {
        return lampMessageBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 6) {
          return (message.LampMessage) msg_;
        }
        return message.LampMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.LampMessage, message.LampMessage.Builder, message.LampMessageOrBuilder> 
        getLampMessageFieldBuilder() {
      if (lampMessageBuilder_ == null) {
        if (!(msgCase_ == 6)) {
          msg_ = message.LampMessage.getDefaultInstance();
        }
        lampMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.LampMessage, message.LampMessage.Builder, message.LampMessageOrBuilder>(
                (message.LampMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 6;
      onChanged();;
      return lampMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorRegisterMessage, message.ElevatorRegisterMessage.Builder, message.ElevatorRegisterMessageOrBuilder> registerMessageBuilder_;
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     * @return Whether the registerMessage field is set.
     */
    @java.lang.Override
    public boolean hasRegisterMessage() {
      return msgCase_ == 7;
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     * @return The registerMessage.
     */
    @java.lang.Override
    public message.ElevatorRegisterMessage getRegisterMessage() {
      if (registerMessageBuilder_ == null) {
        if (msgCase_ == 7) {
          return (message.ElevatorRegisterMessage) msg_;
        }
        return message.ElevatorRegisterMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 7) {
          return registerMessageBuilder_.getMessage();
        }
        return message.ElevatorRegisterMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    public Builder setRegisterMessage(message.ElevatorRegisterMessage value) {
      if (registerMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        registerMessageBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    public Builder setRegisterMessage(
        message.ElevatorRegisterMessage.Builder builderForValue) {
      if (registerMessageBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        registerMessageBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    public Builder mergeRegisterMessage(message.ElevatorRegisterMessage value) {
      if (registerMessageBuilder_ == null) {
        if (msgCase_ == 7 &&
            msg_ != message.ElevatorRegisterMessage.getDefaultInstance()) {
          msg_ = message.ElevatorRegisterMessage.newBuilder((message.ElevatorRegisterMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 7) {
          registerMessageBuilder_.mergeFrom(value);
        }
        registerMessageBuilder_.setMessage(value);
      }
      msgCase_ = 7;
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    public Builder clearRegisterMessage() {
      if (registerMessageBuilder_ == null) {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 7) {
          msgCase_ = 0;
          msg_ = null;
        }
        registerMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    public message.ElevatorRegisterMessage.Builder getRegisterMessageBuilder() {
      return getRegisterMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    @java.lang.Override
    public message.ElevatorRegisterMessageOrBuilder getRegisterMessageOrBuilder() {
      if ((msgCase_ == 7) && (registerMessageBuilder_ != null)) {
        return registerMessageBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 7) {
          return (message.ElevatorRegisterMessage) msg_;
        }
        return message.ElevatorRegisterMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.ElevatorRegisterMessage, message.ElevatorRegisterMessage.Builder, message.ElevatorRegisterMessageOrBuilder> 
        getRegisterMessageFieldBuilder() {
      if (registerMessageBuilder_ == null) {
        if (!(msgCase_ == 7)) {
          msg_ = message.ElevatorRegisterMessage.getDefaultInstance();
        }
        registerMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.ElevatorRegisterMessage, message.ElevatorRegisterMessage.Builder, message.ElevatorRegisterMessageOrBuilder>(
                (message.ElevatorRegisterMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 7;
      onChanged();;
      return registerMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.FaultMessage, message.FaultMessage.Builder, message.FaultMessageOrBuilder> faultMessageBuilder_;
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     * @return Whether the faultMessage field is set.
     */
    @java.lang.Override
    public boolean hasFaultMessage() {
      return msgCase_ == 8;
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     * @return The faultMessage.
     */
    @java.lang.Override
    public message.FaultMessage getFaultMessage() {
      if (faultMessageBuilder_ == null) {
        if (msgCase_ == 8) {
          return (message.FaultMessage) msg_;
        }
        return message.FaultMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 8) {
          return faultMessageBuilder_.getMessage();
        }
        return message.FaultMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    public Builder setFaultMessage(message.FaultMessage value) {
      if (faultMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        faultMessageBuilder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    public Builder setFaultMessage(
        message.FaultMessage.Builder builderForValue) {
      if (faultMessageBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        faultMessageBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    public Builder mergeFaultMessage(message.FaultMessage value) {
      if (faultMessageBuilder_ == null) {
        if (msgCase_ == 8 &&
            msg_ != message.FaultMessage.getDefaultInstance()) {
          msg_ = message.FaultMessage.newBuilder((message.FaultMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 8) {
          faultMessageBuilder_.mergeFrom(value);
        }
        faultMessageBuilder_.setMessage(value);
      }
      msgCase_ = 8;
      return this;
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    public Builder clearFaultMessage() {
      if (faultMessageBuilder_ == null) {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 8) {
          msgCase_ = 0;
          msg_ = null;
        }
        faultMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    public message.FaultMessage.Builder getFaultMessageBuilder() {
      return getFaultMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    @java.lang.Override
    public message.FaultMessageOrBuilder getFaultMessageOrBuilder() {
      if ((msgCase_ == 8) && (faultMessageBuilder_ != null)) {
        return faultMessageBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 8) {
          return (message.FaultMessage) msg_;
        }
        return message.FaultMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.FaultMessage, message.FaultMessage.Builder, message.FaultMessageOrBuilder> 
        getFaultMessageFieldBuilder() {
      if (faultMessageBuilder_ == null) {
        if (!(msgCase_ == 8)) {
          msg_ = message.FaultMessage.getDefaultInstance();
        }
        faultMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.FaultMessage, message.FaultMessage.Builder, message.FaultMessageOrBuilder>(
                (message.FaultMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 8;
      onChanged();;
      return faultMessageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        message.SimulateFaultMessage, message.SimulateFaultMessage.Builder, message.SimulateFaultMessageOrBuilder> simFaultMessageBuilder_;
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     * @return Whether the simFaultMessage field is set.
     */
    @java.lang.Override
    public boolean hasSimFaultMessage() {
      return msgCase_ == 9;
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     * @return The simFaultMessage.
     */
    @java.lang.Override
    public message.SimulateFaultMessage getSimFaultMessage() {
      if (simFaultMessageBuilder_ == null) {
        if (msgCase_ == 9) {
          return (message.SimulateFaultMessage) msg_;
        }
        return message.SimulateFaultMessage.getDefaultInstance();
      } else {
        if (msgCase_ == 9) {
          return simFaultMessageBuilder_.getMessage();
        }
        return message.SimulateFaultMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    public Builder setSimFaultMessage(message.SimulateFaultMessage value) {
      if (simFaultMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        simFaultMessageBuilder_.setMessage(value);
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    public Builder setSimFaultMessage(
        message.SimulateFaultMessage.Builder builderForValue) {
      if (simFaultMessageBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        simFaultMessageBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    public Builder mergeSimFaultMessage(message.SimulateFaultMessage value) {
      if (simFaultMessageBuilder_ == null) {
        if (msgCase_ == 9 &&
            msg_ != message.SimulateFaultMessage.getDefaultInstance()) {
          msg_ = message.SimulateFaultMessage.newBuilder((message.SimulateFaultMessage) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 9) {
          simFaultMessageBuilder_.mergeFrom(value);
        }
        simFaultMessageBuilder_.setMessage(value);
      }
      msgCase_ = 9;
      return this;
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    public Builder clearSimFaultMessage() {
      if (simFaultMessageBuilder_ == null) {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 9) {
          msgCase_ = 0;
          msg_ = null;
        }
        simFaultMessageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    public message.SimulateFaultMessage.Builder getSimFaultMessageBuilder() {
      return getSimFaultMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    @java.lang.Override
    public message.SimulateFaultMessageOrBuilder getSimFaultMessageOrBuilder() {
      if ((msgCase_ == 9) && (simFaultMessageBuilder_ != null)) {
        return simFaultMessageBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 9) {
          return (message.SimulateFaultMessage) msg_;
        }
        return message.SimulateFaultMessage.getDefaultInstance();
      }
    }
    /**
     * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        message.SimulateFaultMessage, message.SimulateFaultMessage.Builder, message.SimulateFaultMessageOrBuilder> 
        getSimFaultMessageFieldBuilder() {
      if (simFaultMessageBuilder_ == null) {
        if (!(msgCase_ == 9)) {
          msg_ = message.SimulateFaultMessage.getDefaultInstance();
        }
        simFaultMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            message.SimulateFaultMessage, message.SimulateFaultMessage.Builder, message.SimulateFaultMessageOrBuilder>(
                (message.SimulateFaultMessage) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 9;
      onChanged();;
      return simFaultMessageBuilder_;
    }

    private boolean tEST_ ;
    /**
     * <code>bool TEST = 10;</code>
     * @return The tEST.
     */
    @java.lang.Override
    public boolean getTEST() {
      return tEST_;
    }
    /**
     * <code>bool TEST = 10;</code>
     * @param value The tEST to set.
     * @return This builder for chaining.
     */
    public Builder setTEST(boolean value) {
      
      tEST_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool TEST = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTEST() {
      
      tEST_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorCommands.WrapperMessage)
  }

  // @@protoc_insertion_point(class_scope:elevatorCommands.WrapperMessage)
  private static final message.WrapperMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new message.WrapperMessage();
  }

  public static message.WrapperMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WrapperMessage>
      PARSER = new com.google.protobuf.AbstractParser<WrapperMessage>() {
    @java.lang.Override
    public WrapperMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WrapperMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WrapperMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WrapperMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public message.WrapperMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

