// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevator.proto

package message;

public interface WrapperMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorCommands.WrapperMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return Whether the elevatorRequest field is set.
   */
  boolean hasElevatorRequest();
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   * @return The elevatorRequest.
   */
  message.ElevatorRequestMessage getElevatorRequest();
  /**
   * <code>.elevatorCommands.ElevatorRequestMessage elevatorRequest = 1;</code>
   */
  message.ElevatorRequestMessageOrBuilder getElevatorRequestOrBuilder();

  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return Whether the schedulerDispatch field is set.
   */
  boolean hasSchedulerDispatch();
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   * @return The schedulerDispatch.
   */
  message.SchedulerDispatchMessage getSchedulerDispatch();
  /**
   * <code>.elevatorCommands.SchedulerDispatchMessage schedulerDispatch = 2;</code>
   */
  message.SchedulerDispatchMessageOrBuilder getSchedulerDispatchOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return Whether the elevatorArrived field is set.
   */
  boolean hasElevatorArrived();
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   * @return The elevatorArrived.
   */
  message.ElevatorArrivedMessage getElevatorArrived();
  /**
   * <code>.elevatorCommands.ElevatorArrivedMessage elevatorArrived = 3;</code>
   */
  message.ElevatorArrivedMessageOrBuilder getElevatorArrivedOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return Whether the elevatorDeparture field is set.
   */
  boolean hasElevatorDeparture();
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   * @return The elevatorDeparture.
   */
  message.ElevatorDepartureMessage getElevatorDeparture();
  /**
   * <code>.elevatorCommands.ElevatorDepartureMessage elevatorDeparture = 4;</code>
   */
  message.ElevatorDepartureMessageOrBuilder getElevatorDepartureOrBuilder();

  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return Whether the floorSensor field is set.
   */
  boolean hasFloorSensor();
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   * @return The floorSensor.
   */
  message.FloorSensorMessage getFloorSensor();
  /**
   * <code>.elevatorCommands.FloorSensorMessage floorSensor = 5;</code>
   */
  message.FloorSensorMessageOrBuilder getFloorSensorOrBuilder();

  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return Whether the lampMessage field is set.
   */
  boolean hasLampMessage();
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   * @return The lampMessage.
   */
  message.LampMessage getLampMessage();
  /**
   * <code>.elevatorCommands.LampMessage lampMessage = 6;</code>
   */
  message.LampMessageOrBuilder getLampMessageOrBuilder();

  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return Whether the registerMessage field is set.
   */
  boolean hasRegisterMessage();
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   * @return The registerMessage.
   */
  message.ElevatorRegisterMessage getRegisterMessage();
  /**
   * <code>.elevatorCommands.ElevatorRegisterMessage registerMessage = 7;</code>
   */
  message.ElevatorRegisterMessageOrBuilder getRegisterMessageOrBuilder();

  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   * @return Whether the faultMessage field is set.
   */
  boolean hasFaultMessage();
  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   * @return The faultMessage.
   */
  message.FaultMessage getFaultMessage();
  /**
   * <code>.elevatorCommands.FaultMessage faultMessage = 8;</code>
   */
  message.FaultMessageOrBuilder getFaultMessageOrBuilder();

  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   * @return Whether the simFaultMessage field is set.
   */
  boolean hasSimFaultMessage();
  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   * @return The simFaultMessage.
   */
  message.SimulateFaultMessage getSimFaultMessage();
  /**
   * <code>.elevatorCommands.SimulateFaultMessage simFaultMessage = 9;</code>
   */
  message.SimulateFaultMessageOrBuilder getSimFaultMessageOrBuilder();

  /**
   * <code>bool TEST = 10;</code>
   * @return The tEST.
   */
  boolean getTEST();

  public message.WrapperMessage.MsgCase getMsgCase();
}
